/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scarike_jni_demo4_Main */

#ifndef _Included_com_scarike_jni_demo4_Main
#define _Included_com_scarike_jni_demo4_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_scarike_jni_demo4_Main
 * Method:    jniArray
 * Signature: ([I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_scarike_jni_demo4_Main_jniArray
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
