/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scarike_jni_demo5_Main */

#ifndef _Included_com_scarike_jni_demo5_Main
#define _Included_com_scarike_jni_demo5_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_scarike_jni_demo5_Main
 * Method:    jniObject
 * Signature: (Lcom/scarike/jni/demo5/User;)Lcom/scarike/jni/demo5/User;
 */
JNIEXPORT jobject JNICALL Java_com_scarike_jni_demo5_Main_jniObject
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
