/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scarike_jni_demo3_Main */

#ifndef _Included_com_scarike_jni_demo3_Main
#define _Included_com_scarike_jni_demo3_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_scarike_jni_demo3_Main
 * Method:    jniString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_scarike_jni_demo3_Main_jniString
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
