/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scarike_jni_demo2_Main */

#ifndef _Included_com_scarike_jni_demo2_Main
#define _Included_com_scarike_jni_demo2_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_scarike_jni_demo2_Main
 * Method:    eleType
 * Signature: (BSIJFDZC)V
 */
JNIEXPORT void JNICALL Java_com_scarike_jni_demo2_Main_eleType
  (JNIEnv *, jobject, jbyte, jshort, jint, jlong, jfloat, jdouble, jboolean, jchar);

#ifdef __cplusplus
}
#endif
#endif
