/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scarike_jni_util_ObjectUtil */

#ifndef _Included_com_scarike_jni_util_ObjectUtil
#define _Included_com_scarike_jni_util_ObjectUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_scarike_jni_util_ObjectUtil
 * Method:    getHeadAString
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_scarike_jni_util_ObjectUtil_getMarkWordAsString
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
