/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scarike_jni_demo1_Main */

#ifndef _Included_com_scarike_jni_demo1_Main
#define _Included_com_scarike_jni_demo1_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_scarike_jni_demo1_Main
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_scarike_jni_demo1_Main_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
